require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../models/Product");
const User = require("../models/User");

const MONGO_URI = process.env.MONGO_URI || "mongodb://127.0.0.1:27017/mart-in";

const products = [
  // Snacks & Beverages
  {
    title: "Nestle Munch Chocolate Wafer Bar",
    description: "Crunchy chocolate wafer bar coated with delicious milk chocolate. Pocket-friendly sweet snack. Net wt: 11.1g.",
    price: 5,
    originalPrice: 5,
    category: "Snacks & Beverages",
    unit: "11.1 g",
    stockQuantity: 200,
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: true,
    discountPercentage: 0,
  },
  {
    title: "Lay's India's Magic Masala Chips (Mini)",
    description: "Crispy potato chips seasoned with authentic Indian spices. Perfect small snack size. Net wt: 12g.",
    price: 5,
    originalPrice: 5,
    category: "Snacks & Beverages",
    unit: "12 g",
    stockQuantity: 250,
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: true,
    discountPercentage: 0,
  },
  {
    title: "Parle Melody Chocolaty Candy Pack",
    description: "Melody hai chocolaty! Delicious caramel exterior with rich chocolate core candy. Net wt: 40g.",
    price: 5,
    originalPrice: 5,
    category: "Snacks & Beverages",
    unit: "40 g",
    stockQuantity: 180,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1575224300306-1b8da36134ec?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: false,
    discountPercentage: 0,
  },
  {
    title: "Parle-G Glucose Biscuits (Handy Pack)",
    description: "India's favorite glucose biscuit filled with goodness of wheat and milk. Ideal with evening chai. Net wt: 50g.",
    price: 10,
    originalPrice: 10,
    category: "Snacks & Beverages",
    unit: "50 g",
    stockQuantity: 300,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: true,
    discountPercentage: 0,
  },
  {
    title: "Kurkure Masala Munch Snack",
    description: "Crispy, crunchy corn puff chips packed with spicy Indian spice blend. Net wt: 85g.",
    price: 20,
    originalPrice: 20,
    category: "Snacks & Beverages",
    unit: "85 g",
    stockQuantity: 120,
    inStock: true,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281358?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: false,
    discountPercentage: 0,
  },
  {
    title: "Lay's Magic Masala Potato Chips",
    description: "Spicy & tangy masala potato chips made from selected farm-fresh potatoes. Net wt: 50g.",
    price: 20,
    originalPrice: 25,
    category: "Snacks & Beverages",
    unit: "50 g",
    stockQuantity: 90,
    inStock: true,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 20,
  },
  {
    title: "Britannia Good Day Cashew Biscuits",
    description: "Rich buttery cookies packed with crunchy cashew nuts. High energy tasty tea snack. Net wt: 120g.",
    price: 28,
    originalPrice: 35,
    category: "Snacks & Beverages",
    unit: "120 g",
    stockQuantity: 110,
    inStock: true,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: true,
    discountPercentage: 20,
  },
  {
    title: "Coca-Cola Original Taste Soft Drink",
    description: "Refreshing carbonated beverage with classic cola flavor. Best served chilled. Vol: 750 ml.",
    price: 38,
    originalPrice: 45,
    category: "Snacks & Beverages",
    unit: "750 ml",
    stockQuantity: 80,
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 15,
  },
  {
    title: "Sprite Lemon-Lime Soft Drink",
    description: "Clear, crisp, lemon-lime flavored sparkling drink with zero caffeine. Vol: 750 ml bottle.",
    price: 38,
    originalPrice: 45,
    category: "Snacks & Beverages",
    unit: "750 ml",
    stockQuantity: 75,
    inStock: true,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 15,
  },
  {
    title: "Maggi 2-Minute Masala Noodles Pack",
    description: "Classic Indian favourite instant noodles with signature spice mix pouch inside. Net wt: 280g (4 Pack).",
    price: 54,
    originalPrice: 60,
    category: "Snacks & Beverages",
    unit: "280 g",
    stockQuantity: 150,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: true,
    discountPercentage: 0,
  },
  {
    title: "Cadbury Dairy Milk Silk Chocolate",
    description: "Ultra-smooth and creamy milk chocolate bar made with rich cocoa butter. Net wt: 60g.",
    price: 75,
    originalPrice: 85,
    category: "Snacks & Beverages",
    unit: "60 g",
    stockQuantity: 95,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 12,
  },
  {
    title: "Haldiram's Nagpur Bhujia Sev",
    description: "Crispy savory snack prepared from tepary bean flour and blend of traditional spices. Net wt: 200g.",
    price: 52,
    originalPrice: 60,
    category: "Snacks & Beverages",
    unit: "200 g",
    stockQuantity: 80,
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 13,
  },

  // Dairy & Bakery
  {
    title: "Amul Taaza Toned Fresh Milk",
    description: "Pasteurized homogenized toned milk with 3.0% fat and 8.5% SNF. Net vol: 500ml pouch.",
    price: 27,
    originalPrice: 28,
    category: "Dairy & Bakery",
    unit: "500 ml",
    stockQuantity: 150,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: false,
    discountPercentage: 0,
  },
  {
    title: "Amul Pasteurized Salted Butter",
    description: "Utterly butterly delicious creamery butter made from pure cow and buffalo milk fat. Net wt: 100g pack.",
    price: 54,
    originalPrice: 58,
    category: "Dairy & Bakery",
    unit: "100 g",
    stockQuantity: 90,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: true,
    discountPercentage: 7,
  },
  {
    title: "Amul Fresh Malai Paneer",
    description: "Soft & smooth cottage cheese block crafted from pasteurized milk. Net wt: 200g.",
    price: 90,
    originalPrice: 105,
    category: "Dairy & Bakery",
    unit: "200 g",
    stockQuantity: 50,
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 14,
  },
  {
    title: "Britannia 100% Whole Wheat Bread",
    description: "Healthy whole wheat bread baked fresh daily with zero trans-fat. Net wt: 400g loaf.",
    price: 45,
    originalPrice: 50,
    category: "Dairy & Bakery",
    unit: "400 g",
    stockQuantity: 70,
    inStock: true,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: true,
    discountPercentage: 0,
  },
  {
    title: "Amul Processed Cheese Slices",
    description: "Individually wrapped creamy cheese slices. Net wt: 200g (10 slices).",
    price: 135,
    originalPrice: 155,
    category: "Dairy & Bakery",
    unit: "200 g",
    stockQuantity: 40,
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 13,
  },

  // Fresh Produce
  {
    title: "Fresh Shimla Red Apples",
    description: "Crispy, sweet red apples sourced directly from Himachal Pradesh orchards. Net wt: 1 kg.",
    price: 135,
    originalPrice: 160,
    category: "Fresh Produce",
    unit: "1 kg",
    stockQuantity: 60,
    inStock: true,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 15,
  },
  {
    title: "Fresh Farm Red Onions (Pyaz)",
    description: "Pungent and firm farm-fresh red onions essential for daily Indian curries. Net wt: 1 kg.",
    price: 32,
    originalPrice: 40,
    category: "Fresh Produce",
    unit: "1 kg",
    stockQuantity: 200,
    inStock: true,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cf?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: true,
    discountPercentage: 20,
  },
  {
    title: "Hybrid Red Tomatoes (Tamatar)",
    description: "Firm, tangy red tomatoes packed with vitamin C. Net wt: 1 kg.",
    price: 36,
    originalPrice: 45,
    category: "Fresh Produce",
    unit: "1 kg",
    stockQuantity: 180,
    inStock: true,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 20,
  },

  // Staples & Food Grains
  {
    title: "Aashirvaad Shudh Chakki Atta",
    description: "100% pure whole wheat flour processed using traditional stone-chakki grinding. Net wt: 5 kg.",
    price: 235,
    originalPrice: 275,
    category: "Staples & Food Grains",
    unit: "5 kg",
    stockQuantity: 100,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 15,
  },
  {
    title: "India Gate Basmati Rice Super",
    description: "Aromatic long-grain aged Basmati rice. Fluffy non-sticky grains. Net wt: 1 kg.",
    price: 175,
    originalPrice: 210,
    category: "Staples & Food Grains",
    unit: "1 kg",
    stockQuantity: 80,
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 16,
  },

  // Household & Personal Care
  {
    title: "Dettol Antiseptic Soap Bar (Mini)",
    description: "Trusted germ protection bathing soap bar in a convenient travel size. Net wt: 45g.",
    price: 10,
    originalPrice: 10,
    category: "Household & Personal Care",
    unit: "45 g",
    stockQuantity: 200,
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1607006482602-76ca0fd2f477?w=500&auto=format&fit=crop&q=80",
    isOnOffer: false,
    isBogo: true,
    discountPercentage: 0,
  },
  {
    title: "Dove Cream Beauty Bathing Bar",
    description: "Gentle skin cleansing bar containing 1/4th moisturizing cream. Net wt: 100g.",
    price: 58,
    originalPrice: 68,
    category: "Household & Personal Care",
    unit: "100 g",
    stockQuantity: 120,
    inStock: true,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: true,
    discountPercentage: 15,
  },
  {
    title: "Surf Excel Easy Wash Detergent Powder",
    description: "Advanced stain removal washing powder that dissolves easily. Net wt: 1 kg.",
    price: 130,
    originalPrice: 150,
    category: "Household & Personal Care",
    unit: "1 kg",
    stockQuantity: 90,
    inStock: true,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=500&auto=format&fit=crop&q=80",
    isOnOffer: true,
    isBogo: false,
    discountPercentage: 13,
  },
];

async function seedDB() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Connected to MongoDB for seed & admin setup...");
    
    // Clear products and seed
    await Product.deleteMany({});
    console.log("Cleared old products.");
    const insertedProducts = await Product.insertMany(products);
    console.log(`Successfully seeded ${insertedProducts.length} products with BOGO tags!`);

    // Create default Admin User
    const adminEmail = "admin@martin.com";
    const existingAdmin = await User.findOne({ email: adminEmail });
    if (!existingAdmin) {
      await User.create({
        name: "Mart-In Admin",
        email: adminEmail,
        password: "admin123",
        role: "admin",
      });
      console.log("Created default Admin user: admin@martin.com / admin123");
    } else {
      existingAdmin.role = "admin";
      await existingAdmin.save();
      console.log("Updated default Admin user role to admin.");
    }

    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
}

seedDB();
